name = "notelab-client"
main = "worker.js"
compatibility_date = "2026-05-28"
assets = { directory = "dist", binding = "ASSETS", html_handling = "none", not_found_handling = "single-page-application" }
routes = [
  { pattern = "app.notelab.io", custom_domain = true }
]

services = [
  { binding = "API_SERVICE", service = "notelab-server" }
]

[observability]
enabled = true
