#!/usr/bin/env node

import { randomBytes } from "node:crypto"
import { constants } from "node:fs"
import { access, readFile, writeFile } from "node:fs/promises"
import { createInterface } from "node:readline/promises"
import { fileURLToPath } from "node:url"
import path from "node:path"
import process from "node:process"
import { spawn } from "node:child_process"

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..")
const defaultEnvFile = path.join(repositoryRoot, ".env.selfhost.development")
const envFile = path.resolve(
  process.env.ZILOBASE_SELFHOST_ENV_FILE || defaultEnvFile,
)
const projectName = process.env.ZILOBASE_SELFHOST_PROJECT_NAME || "zilobase-dev"
const command = process.argv[2]
const commandArgs = new Set(process.argv.slice(3))

if (!new Set(["up", "logs", "down", "reset", "test"]).has(command)) {
  fail("Usage: node scripts/selfhost/manage.mjs <up|logs|down|reset|test> [--yes]")
}

if (command === "test") {
  await run(process.execPath, ["scripts/selfhost/test.mjs", ...process.argv.slice(3)], {
    cwd: repositoryRoot,
  })
  process.exit(0)
}

if (command === "up") {
  await ensureDevelopmentEnvironment()
  await compose([
    "up",
    "-d",
    commandArgs.has("--no-build") ? "--no-build" : "--build",
    "--wait",
  ])
  await printConnectionInstructions()
  process.exit(0)
}

if (command === "logs") {
  await requireDevelopmentEnvironment()
  await compose(["logs", "--follow", "--tail", "200"])
  process.exit(0)
}

if (command === "down") {
  await requireDevelopmentEnvironment()
  await compose(["down", "--remove-orphans"])
  console.info("Self-hosted containers stopped. Database and object-storage volumes were preserved.")
  process.exit(0)
}

await requireDevelopmentEnvironment()
await confirmReset()
await compose(["down", "--volumes", "--remove-orphans"])
console.info("Self-hosted containers and named data volumes were removed.")

async function ensureDevelopmentEnvironment() {
  if (await exists(envFile)) return

  const httpPort = process.env.ZILOBASE_DEV_HTTP_PORT || "8787"
  const minioPort = process.env.MINIO_DEV_API_PORT || "9000"
  const mailpitPort = process.env.MAILPIT_DEV_UI_PORT || "8025"
  const serverOrigin = `http://127.0.0.1:${httpPort}`

  const contents = [
    "# Generated by npm run selfhost:up. Keep this file private.",
    `COMPOSE_PROJECT_NAME=${projectName}`,
    `ZILOBASE_IMAGE=${process.env.ZILOBASE_SELFHOST_IMAGE || "zilobase-dev:local"}`,
    `ZILOBASE_PULL_POLICY=${process.env.ZILOBASE_SELFHOST_PULL_POLICY || "never"}`,
    "ZILOBASE_SITE_ADDRESS=http://127.0.0.1",
    "ZILOBASE_STORAGE_SITE_ADDRESS=http://127.0.0.1",
    `ZILOBASE_DEV_HTTP_PORT=${httpPort}`,
    `MINIO_DEV_API_PORT=${minioPort}`,
    `MAILPIT_DEV_UI_PORT=${mailpitPort}`,
    `CLIENT_URL=${serverOrigin}`,
    `BETTER_AUTH_URL=${serverOrigin}`,
    `S3_PUBLIC_ENDPOINT=http://127.0.0.1:${minioPort}`,
    `BETTER_AUTH_SECRET=${secret(48)}`,
    `ZILOBASE_BOOTSTRAP_TOKEN=${secret(48)}`,
    "POSTGRES_DB=zilobase",
    "POSTGRES_USER=zilobase",
    `POSTGRES_PASSWORD=${secret(32)}`,
    "MINIO_BUCKET=zilobase",
    "MINIO_ROOT_USER=zilobase",
    `MINIO_ROOT_PASSWORD=${secret(32)}`,
    "EMAIL_FROM=Zilobase <hello@zilobase.local>",
    "SMTP_HOST=mailpit",
    "SMTP_PORT=1025",
    "SMTP_SECURE=false",
    "SMTP_USER=",
    "SMTP_PASSWORD=",
    "GOOGLE_CLIENT_ID=",
    "GOOGLE_CLIENT_SECRET=",
    "OPENAI_API_KEY=",
    "",
  ].join("\n")

  await writeFile(envFile, contents, { flag: "wx", mode: 0o600 })
  console.info(`Generated private development secrets in ${path.relative(repositoryRoot, envFile)}`)
}

async function requireDevelopmentEnvironment() {
  if (!(await exists(envFile))) {
    fail(`Missing ${path.relative(repositoryRoot, envFile)}. Run npm run selfhost:up first.`)
  }
}

async function printConnectionInstructions() {
  const values = parseEnv(await readFile(envFile, "utf8"))
  const httpPort = values.ZILOBASE_DEV_HTTP_PORT || "8787"
  const mailpitPort = values.MAILPIT_DEV_UI_PORT || "8025"
  const serverUrl = `http://127.0.0.1:${httpPort}`
  const setupUrl = `${serverUrl}/setup`
  const connectUrl = `zilobase://connect?server=${encodeURIComponent(serverUrl)}`

  console.info("")
  console.info("Zilobase self-host is ready.")
  console.info(`Server:             ${serverUrl}`)
  console.info(`Initial setup:      ${setupUrl}`)
  console.info(`Development email:  http://127.0.0.1:${mailpitPort}`)
  console.info(`Desktop connection: ${connectUrl}`)
  console.info("")
  console.info("For first-time setup, copy ZILOBASE_BOOTSTRAP_TOKEN from")
  console.info(`${path.relative(repositoryRoot, envFile)} into the setup page. The token is never placed in a URL.`)
}

async function confirmReset() {
  if (commandArgs.has("--yes")) return

  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    fail("Reset deletes all local self-hosted data. Re-run with --yes to confirm.")
  }

  const prompt = createInterface({ input: process.stdin, output: process.stdout })
  const answer = await prompt.question(
    `Type "reset" to delete the ${projectName} database and object-storage volumes: `,
  )
  prompt.close()

  if (answer.trim().toLowerCase() !== "reset") {
    fail("Reset cancelled.")
  }
}

async function compose(args) {
  return run(
    "docker",
    [
      "compose",
      "--project-name",
      projectName,
      "--env-file",
      envFile,
      "-f",
      "docker-compose.yml",
      "-f",
      "docker-compose.dev.yml",
      "--profile",
      "dev",
      ...args,
    ],
    { cwd: repositoryRoot },
  )
}

function run(executable, args, options) {
  return new Promise((resolve, reject) => {
    const child = spawn(executable, args, { ...options, stdio: "inherit" })
    child.once("error", reject)
    child.once("exit", (code, signal) => {
      if (code === 0) resolve()
      else reject(new Error(`${executable} exited with ${signal || code}`))
    })
  })
}

function parseEnv(contents) {
  return Object.fromEntries(
    contents
      .split(/\r?\n/)
      .filter((line) => line && !line.startsWith("#") && line.includes("="))
      .map((line) => {
        const separator = line.indexOf("=")
        return [line.slice(0, separator), line.slice(separator + 1)]
      }),
  )
}

function secret(bytes) {
  return randomBytes(bytes).toString("base64url")
}

async function exists(filename) {
  try {
    await access(filename, constants.F_OK)
    return true
  } catch {
    return false
  }
}

function fail(message) {
  console.error(message)
  process.exit(1)
}
